### ISSUE TITLE
赞，终于有一个更和我个人胃口的公开示例库了

### ISSUE THREAD

**Issue by oldwinter** [juestchaos/Obsidian-Plug-and-Play#1]
就是有个问题，为啥默认不使用.obsidian这个配置，我pull下来以后，它默认用的是.obsdian这个文件夹，少了1个字母。我还以为你一个插件都没用呢。

**Comment by juestchaos** [comment]
这个可以修改，应该是我的笔误

**Comment by juestchaos** [comment]
> 
已经修复，可以查看 [V1.0.6](https://github.com/juestchaos/Obsidian-Plug-and-Play/releases/tag/0.1.6)
