### ISSUE TITLE
metadata和banner问题

### ISSUE THREAD

**Issue by pikawindy** [juestchaos/Obsidian-Plug-and-Play#2]
![Snipaste_2022-08-26_16-39-02](https://user-images.githubusercontent.com/63467634/186861490-6a21b9a7-85f0-4746-bc34-228a206fa3eb.jpg)

一旦我添加了yaml，打开阅读视图，表头就会有大段空白？这空白是banner？请问如何取消这东西啊

**Comment by juestchaos** [comment]
抱歉，我这里没有浮现你说的问题，如果可以的化，可以尝试最新的 releases。
或者提供给我更多信息
![image](https://user-images.githubusercontent.com/241007/188061702-2903a717-ab17-4e45-b818-b6a95a273d3e.png)

**Comment by juestchaos** [comment]
抱歉，我这里没有浮现你说的问题，如果可以的化，可以尝试最新的 releases。
或者提供给我更多信息
![image](https://user-images.githubusercontent.com/241007/188061702-2903a717-ab17-4e45-b818-b6a95a273d3e.png)

**Comment by juestchaos** [comment]
您好，我复现并定位的问题如下：
应该是banners 插件在没有使用 bannericon 添加到 yaml 区的时候，会产生此类问题。
已经[v0.1.13](https://github.com/juestchaos/Obsidian-Plug-and-Play/releases/tag/0.1.13)中修复了此问题。

**Comment by juestchaos** [comment]
您好，我复现并定位的问题如下：
应该是banners 插件在没有使用 bannericon 添加到 yaml 区的时候，会产生此类问题。
已经[v0.1.13](https://github.com/juestchaos/Obsidian-Plug-and-Play/releases/tag/0.1.13)中修复了此问题。
