### ISSUE TITLE
状态栏菜单按钮异常

### ISSUE THREAD

**Issue by ipodtun** [juestchaos/Obsidian-Plug-and-Play#4]
你好，很喜欢这个开箱即用库，简单干净。提个小bug，底下状态栏的两个菜单按钮点击展示异常
![image](https://user-images.githubusercontent.com/10530203/200859014-228b5fd1-8fd3-47ae-b6e3-6553052756ad.png)

**Comment by juestchaos** [comment]
实测反馈有效
通过还原到 Obsidian 默认的主题，并关闭所有影响的插件进行了测试，依然无法修正这个问题。
可能是【Enhanced-editing】 插件的渲染问题。
该插件的 Issues 上有类似讨论[#44](https://github.com/obsidian-canzi/Enhanced-editing/issues/44)，但还没有回应，我会关注。
当前库 版本 [v0.2.5](https://github.com/juestchaos/Obsidian-Plug-and-Play/releases/tag/0.2.5) 已经移除了该插件，采用 【editing-toolbar】代替。当然这种方法会产生
